spring:
  datasource:
    url: jdbc:h2:mem:postgresql;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
jwt:
  sessionTime: 120000000
  secret: secret_key


